[package]
name = "on-the-dl"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
reqwest = { version = "0.11.18", default-features = false }

[dev-dependencies]
tokio = { version = "1.0", default-features = false, features = ["macros", "rt-multi-thread"] }
